# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 6
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

animations {
    enabled = yes

    # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more


    # Custom by Gui 

    # Animation when change workspace
    bezier = overshot, 0.05, 0.9, 0.1, 1.05
    animation = workspaces, 1, 7, overshot, slidefade 10%
    animation = specialWorkspace, 1, 6, overshot, slidevert

    #animation = hyprlock, 1, 5, easeInOutCubic, fade
}